version: '2'
volumes:
  weewx-data:
services:
  weather:
    build: ./weather
    container_name: weather
    restart: unless-stopped
    privileged: true
    devices: 
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      TEMPLATE_STATION_LOCATION: Rockland
      TEMPLATE_STATION_LATITUDE: "0.0"
      TEMPLATE_STATION_LONGITUDE: "0.0"
      TEMPLATE_STATION_ALTITUDE: "0.0"
      INFLUX_SERVER_URL: ""
      INFLUX_BUCKET: ""
      INFLUX_API_TOKEN: ""
      INFLUX_MEASUREMENT: ""
  basicstation:
    image: xoseperez/basicstation
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host # read main interface MAC
    devices: 
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      DEVICE: "AUTO"
      GATEWAY_EUI_SOURCE: "eth0"
      HAS_GPS: "0" # 1 if GNSS module
      INTERFACE: "USB" # USB or SPI
      MODEL: "SX1302"
      TC_KEY: "" # LNS registration key from TTN interface
      TLS_SNI: "true"
      TTS_REGION: "nam1"
      TTS_TENANT: "neracoos"
  alloy:
    build: ./grafana/weather-alloy
    privileged: true
    environment:
      ARCH: "arm64"
      ALLOY_METRICS_URL: "https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push" 
      ALLOY_METRICS_ID: "2413093"
      ALLOY_SCRAPE_INTERVAL: "60s"
      ALLOY_LOGS_URL: "https://logs-prod-036.grafana.net/loki/api/v1/push"
      ALLOY_LOGS_ID: "1202223"
      ALLOY_API_KEY: "" # Integration key for Grafana Cloud, set in Balena Cloud
  grafana: