version: '2'
volumes:
  weewx-data:
services:
  weewx:
    build: ./weewx
    privileged: true
    devices: 
      - "/dev/ttyUSB0:/dev/ttyUSB0"
  basicstation:
    image: ./lorawan
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host # read main interface MAC
    environment:
      MODEL: "SX1302"
      TC_KEY: "" 
      INTERFACE: "USB"
      TTS_REGION: "nam1"
    devices: 
      - "/dev/ttyUSB0:/dev/ttyUSB0"