# pylint: disable=too-many-locals
"""
Command line interface for working with buoy data and firmware.

Documentation is autogenerated and published to:
https://hurricane-island.github.io/pen-bay-marine-data/#penbay-buoys

Features:
- Combine column wise and row wise
- Match weather API as much as possible

"""

import re
from pathlib import Path
from enum import Enum
from datetime import datetime, timedelta
from math import radians, cos, sin, sqrt, atan2
from hashlib import md5
from numpy import concatenate, array, argsort
from pandas import read_csv, DataFrame, concat
from influxdb_client_3 import InfluxDBClient3
from matplotlib import pyplot as plt, dates as mdates
from matplotlib.patches import Circle
from matplotlib.markers import MarkerStyle
from ioos_qc.config import Config
from ioos_qc.streams import PandasStream
from ioos_qc.stores import PandasStore
from scipy.io import loadmat
from pyproj import Transformer
import gpxpy
import gpxpy.gpx
import click
from lib import (
    Source,
    influx_options,
    plot_options,
    boxplot,
    influx_host,
    influx_api_token,
    test_observed_property,
    Frequency,
    ImageFormat,
)

DATA_DIR = Path(__file__).parent / "data"
FIGURES_DIR = Path(__file__).parent / "figures"
EXPORT_DIR = Path(__file__).parent / "export"
FIRMWARE_DIR = Path(__file__).parent / "firmware"
TEMPLATE_DIR = Path(__file__).parent / "templates"
CABLE_DIR = Path(__file__).parent / "cable"
transformer = Transformer.from_crs("EPSG:4326", "EPSG:32619", always_xy=True)


class ClickOptions(Enum):
    """
    Available commands for buoy data processing.
    """

    # file and firmware commands
    LIST = "list"
    DESCRIBE = "describe"
    TEMPLATE = "template"
    EXPORT = "export"
    # groups
    FILE = "file"
    BUOYS = "buoys"
    PLOT = "plot"
    FIRMWARE = "firmware"
    DB = "db"
    # plotting commands
    TAIL = "tail"
    DATASTREAM = "datastream"


class StationName(Enum):
    """
    Supported buoy station names.
    """

    WYNKEN = "wynken"
    BLYNKEN = "blynken"


class TableName(Enum):
    """
    Supported data table names.
    """

    DIAGNOSTIC = "Ai1"
    SONDE = "SondeValues"


class VendoredNames(Enum):
    """
    Names that are used in the raw data but don't conform to CF Metadata standards.
    These are mapped to `StandardNames` for use in the CLI and plotting functions.
    """

    SEA_WATER_TEMPERATURE = "External_Temp"
    SEA_WATER_SALINITY = "Salinity"
    SEA_WATER_CHLOROPHYLL_RFU = "Chlorophyll_RFU"
    SEA_WATER_PHYCOERYTHRIN_RFU = "BGA_PE_RFU"
    BAROMETRIC_PRESSURE = "Pressure_abs"
    BATTERY_VOLTAGE = "BatteryVoltage"
    WATER_PRESSURE = "Pressure_mH2O"
    DISSOLVED_OXYGEN = "ODO"
    DISSOLVED_OXYGEN_SATURATION = "ODO_Sat"


class StandardNames(Enum):
    """
    Supported data series names.
    """

    SEA_WATER_TEMPERATURE = "sea_water_temperature"
    MASS_CONCENTRATION_OF_OXYGEN_IN_SEA_WATER = (
        "mass_concentration_of_oxygen_in_sea_water"
    )
    SEA_WATER_SALINITY = "sea_water_salinity"
    SEA_WATER_CHLOROPHYLL_RFU = "sea_water_chlorophyll_rfu"
    SEA_WATER_PHYCOERYTHRIN_RFU = "sea_water_phycocerythrin_rfu"
    BAROMETRIC_PRESSURE = "barometric_pressure"
    BATTERY_VOLTAGE = "battery_voltage"
    WATER_PRESSURE = "water_pressure"
    DISSOLVED_OXYGEN = "dissolved_oxygen"
    DISSOLVED_OXYGEN_SATURATION = "dissolved_oxygen_saturation"


# pylint: disable=too-few-public-methods
class ObservedProperty:
    """
    Abstraction for a single observed property, mapping
    multiple sources into a single Schema based on CF Metadata
    standards.
    """

    name: str
    units: str
    campbell_scientific: Source

    def __init__(self, name: str, unit: str, campbell_scientific: Source):
        self.name = name
        self.unit = unit
        self.campbell_scientific = campbell_scientific


@click.group(name=ClickOptions.BUOYS.value)
def buoys():
    """
    Command line interface for working with buoy data and firmware.
    """


@click.group(name=ClickOptions.FIRMWARE.value)
def firmware():
    """
    Command line interface for working with buoy data and firmware.
    """


@click.group(name=ClickOptions.PLOT.value)
def plot():
    """
    Commands that generate plots using buoy data.
    """


@click.group(name=ClickOptions.FILE.value)
def file_group():
    """
    Commands that interact with the buoy data file system.
    """


@click.group(name=ClickOptions.DB.value)
def database():
    """
    Commands that interact with the buoy database.
    """


station_name = click.argument(
    "name", type=click.Choice(StationName, case_sensitive=False)
)
data_table = click.argument("table", type=click.Choice(TableName, case_sensitive=False))


def source_options(function):
    """
    Choose weather station and observation series. Re-usable decorator
    for commands that need to select a station and series.
    """
    function = click.argument(
        "series", type=click.Choice(StandardNames, case_sensitive=False)
    )(function)
    function = data_table(function)
    function = station_name(function)
    return function


# Subcommands assignment
buoys.add_command(plot)
buoys.add_command(firmware)
buoys.add_command(file_group)
buoys.add_command(database)


@file_group.command(name=ClickOptions.LIST.value)
def buoys_file_list():
    """
    List available stations from static data.
    """
    files = sorted(DATA_DIR.glob("*.dat"))
    seen = set()
    for f in files:
        station = f.stem.split("_")[0]
        if station not in seen:
            seen.add(station)
    for each in sorted(seen):
        print(each)


def read_single_campbell_logger_file(file: Path) -> DataFrame:
    """
    Read a single Campbell logger file and return a DataFrame.
    """
    df = read_csv(file, header=[1, 2, 3], na_values=["NAN"], parse_dates=[0])
    ts_col = df.columns[0]
    return df.set_index(ts_col)


def read_campbell_logger_files(files: list[Path]) -> DataFrame:
    """
    Read multiple Campbell logger files and return a single DataFrame.
    """
    all_data = []
    for file in sorted(files):
        df = read_single_campbell_logger_file(file)
        # Add metadata column to be able to select overlapping data later without a join
        time_recovered = file.stem.split("_")[2]
        df["TimeRecovered"] = datetime.strptime(time_recovered, "%Y-%m-%dT%H-%M")
        all_data.append(df)
    return concat(all_data).dropna(how="all", axis=1)


def filter_buoy_flat_files(name: StationName, table: TableName):
    """
    Filter buoy flat files based on command line options.
    """

    def filter_prefix(f: Path) -> bool:
        lower_name = f.stem.lower()
        station_match = name.value.lower() in lower_name
        table_match = table.value.lower() in lower_name
        return station_match and table_match

    return filter(filter_prefix, DATA_DIR.glob("*.dat"))


@file_group.command(name=ClickOptions.DESCRIBE.value)
@station_name
@data_table
def buoys_file_describe(name: StationName, table: TableName):
    """
    Summarize available data for a station.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    summary = df.describe().T.drop(columns=["25%", "75%", "std"])
    print("\nSamples:\n")
    print(summary)


class TestTypes(Enum):
    """
    Supported QARTOD test types.
    """

    GROSS_RANGE = "gross_range"
    RATE_OF_CHANGE = "rate_of_change"
    SPIKE = "spike"
    CLIMATOLOGY = "climatology"
    FLAT_LINE = "flat_line"
    ROLLUP = "rollup"


@plot.command(name=ClickOptions.TAIL.value)
@source_options
@plot_options
@click.option("--qartod", default="qartod.yaml", help="QARTOD configuration file")
@click.option("--days", default=30, help="Number of days to plot")
@click.option(
    "--test",
    default=TestTypes.ROLLUP,
    type=click.Choice(TestTypes, case_sensitive=False),
    help="QARTOD test to plot",
)
def buoys_plot_tail(
    name: StationName,
    table: TableName,
    series: StandardNames,
    qartod: str,
    days: int,
    test: TestTypes,
    image_format: ImageFormat = ImageFormat.PNG,
):
    """
    Plot the most recent data from a buoy for a single data stream.
    """
    end: datetime = datetime.now()
    start: datetime = end - timedelta(days=days)
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    mask = df.index > start
    df = df[mask].sort_values("TimeRecovered").sort_index(kind="stable")
    df = df[~df.index.duplicated(keep="first")]
    df = df.asfreq("h")
    renamed = []
    units = {}
    for col in df.columns:
        try:
            vendor_name = VendoredNames(col[0])
            std_name = StandardNames[vendor_name.name]
            renamed.append(std_name.value)
        except (KeyError, ValueError):
            renamed.append(col[0])
        units[renamed[-1]] = col[1]
    df.columns = renamed

    fig, ax = plt.subplots(figsize=(7.5, 3))

    ax.plot(
        df.index,
        df[series.value],
        color="grey",
        linestyle="dashed",
        linewidth=1,
        zorder=1,
        label="raw",
    )
    ylim = (None, None)
    if qartod is not None:
        qa_path = Path(__file__).parent / "qartod.yaml"
        if qa_path.exists():
            config = Config(qa_path)
        else:
            raise click.ClickException(
                f"QARTOD configuration file not found: {qa_path}"
            )
        flags = PandasStream(df.reset_index(names="time"), time="time").run(config)
        store = PandasStore(flags)
        result = store.save().set_index("time")
        frames: dict[str, list[str]] = {}
        for each in result.columns:
            _series, _name = each.split("_qartod_")
            if _series not in frames:
                frames[_series] = []
            frames[_series].append(_name)
        by_observed_property = []
        for items in frames.items():
            by_observed_property.append(test_observed_property(result, *items))
        qa = (
            concat(by_observed_property, axis=0)
            .groupby("observed_property")
            .get_group(series.value)[test.value]
        )
        suspect = df[qa == 3][series.value]
        failed = df[qa == 4][series.value]
        remaining = df[qa < 3][series.value].asfreq("h")
        ax.scatter(
            suspect.index,
            suspect,
            label="suspect",
            color="orange",
            marker="x",
            zorder=0,
        )
        ax.scatter(
            failed.index, failed, label="failed", color="red", marker="x", zorder=0
        )
        ax.plot(
            remaining.index,
            remaining,
            color="black",
            linestyle="solid",
            linewidth=1,
            zorder=2,
            label="filtered",
        )
        # ylim = (remaining.min(), remaining.max())

    display_name = series.value.replace("_", " ").title()
    if start.year == end.year:
        year_range = f"{start.year}"
    else:
        year_range = f"{start.year}-{end.year}"
    plt.title(f"{name.value} {display_name} {year_range}".title())
    ax.set_xlabel("Date")
    ax.xaxis.set_tick_params(rotation=45)
    ax.set_xlim(max(start, df.index.min()), end)
    ax.set_ylim(*ylim)
    ax.xaxis.set_major_locator(mdates.DayLocator(interval=(days // 8) + 2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))  # Customize format
    if units is not None:
        ax.set_ylabel(f"{units[series.value]}")
    ax.legend(loc="best")
    fig.tight_layout()
    filepath = (
        FIGURES_DIR
        / ClickOptions.TAIL.value
        / name.value
        / f"{series.value}.{image_format.value}"
    )
    filepath.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(filepath, dpi=300, bbox_inches="tight")


@plot.command(name="cable")
@station_name
def buoys_plot_cable(name: StationName):
    """
    Plot the mooring tension diagram from the WHOI cable simulation.
    """
    low = CABLE_DIR / f"{name.value}-low.mat"
    high = CABLE_DIR / f"{name.value}-high.mat"
    if not low.exists() or not high.exists():
        raise click.ClickException(
            f"Missing cable simulation .mat files for station '{name.value}' (expected {low.name} and {high.name} under {CABLE_DIR})"
        )
    low_data = loadmat(low)
    high_data = loadmat(high)
    fig, ax = plt.subplots(figsize=(4, 3))
    x = concatenate([low_data["x"], high_data["x"]])
    y = concatenate([low_data["z"], high_data["z"]])
    z = concatenate([low_data["T"], high_data["T"]])
    handle = ax.scatter(x, y, c=z, s=2, cmap="spring", label="Mooring")
    ax.vlines(
        low_data["x"].max(),
        ymin=0.0,
        ymax=low_data["z"].max(),
        colors="black",
        linestyles="solid",
        label="Low Tide",
    )
    ax.vlines(
        high_data["x"].max(),
        ymin=0.0,
        ymax=high_data["z"].max(),
        colors="black",
        linestyles="dashed",
        label="High Tide",
    )
    ax.hlines(
        high_data["depth"],
        xmin=0.0,
        xmax=high_data["x"].max(),
        colors="black",
        linestyles="dashed",
    )
    ax.hlines(
        low_data["depth"],
        xmin=0.0,
        xmax=low_data["x"].max(),
        colors="black",
        linestyles="solid",
    )
    ax.set_aspect(1.0)
    fig.colorbar(handle, label="Tension (N)", shrink=0.5)
    ax.set_ylim(y.min(), None)
    ax.set_xlim(x.min(), None)
    ax.set_xlabel("Displacement (m)")
    ax.set_ylabel("Water Level (m)")
    ax.legend(loc="best")
    filename = FIGURES_DIR / "cable" / name.value / "mooring-tension.png"
    Path(filename).parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(filename, bbox_inches="tight", dpi=300)


def predicted_watch_circle(
    center_xy: tuple[float, float],
    station: StationName,
    color: str,
    scale: float = 1.0,
    label: str | None = None,
) -> list[Circle]:
    """
    Generate a predicted watch circle based on the planned deployment location.
    """
    predicted: list[Circle] = []
    for each, circle_label, ls in [("low", label, "solid"), ("high", None, "dashed")]:
        mat_path = CABLE_DIR / f"{station.value}-{each}.mat"
        if not mat_path.exists():
            raise click.ClickException(f"Missing cable simulation file: {mat_path}")
        data = loadmat(mat_path)
        radius = float(data["x"].max()) * scale
        predicted.append(
            Circle(
                center_xy,
                radius=radius,
                color=color,
                fill=False,
                linestyle=ls,
                label=circle_label,
            )
        )
    return predicted


def haversine(lon1, lat1, lon2, lat2):
    R = 6371000.0  # Earth radius in meters

    phi1, phi2 = radians(lat1), radians(lat2)
    delta_phi = radians(lat2 - lat1)
    delta_lambda = radians(lon2 - lon1)
    a = sin(delta_phi / 2) ** 2 + cos(phi1) * cos(phi2) * sin(delta_lambda / 2) ** 2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c  # Distance in meters


@plot.command(name="locations")
@station_name
@click.option("--latitude", required=True, type=float)
@click.option("--longitude", required=True, type=float)
@click.option(
    "--distance",
    required=True,
    type=float,
    help="filter GPS points by distance from planned deployment location (meters)",
)
@click.option(
    "--satellites", required=True, type=int, help="minimum number of satellites"
)
@click.option(
    "--cable",
    is_flag=True,
    help="include predicted watch circle from WHOI cable simulation",
)
def buoys_plot_locations(
    name, latitude, longitude, distance=100.0, satellites=4, cable=False
):
    """
    Plot the lat and long of the buoy hourly over the course of the deployment period.
    This only uses historical data contained in local raw files. Compare it to the
    deployment location of the anchor and the watch circle predicted by WHOI Cable
    simulations.
    """
    table = TableName.DIAGNOSTIC
    lat_name = "Latitude"
    lon_name = "Longitude"
    sat_name = "GPSSatellitesInView"
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    lat = df[lat_name].to_numpy().flatten()
    lon = df[lon_name].to_numpy().flatten()
    satellite_count = df[sat_name].to_numpy().flatten()
    planned_gps = (longitude, latitude)  # original

    def compute_distance(gps):
        return haversine(*planned_gps, *gps)

    mask = (
        (array(list(map(compute_distance, zip(lon, lat)))) < distance)
        & (satellite_count >= satellites)
        & (df.index > datetime(2026, 1, 1))
    )  # filter out erroneous GPS points and early data

    filtered_lon = lon[mask]
    filtered_lat = lat[mask]
    if filtered_lon.size == 0:
        raise click.ClickException(
            "No GPS points remain after filtering; try increasing --distance, lowering --satellites, or adjusting the date filter."
        )
    cx, cy = transformer.transform(filtered_lon.mean(), filtered_lat.mean())
    filtered_sat = satellite_count[mask]

    fig, ax = plt.subplots(figsize=(3, 4))

    sort_ind = argsort(
        filtered_sat
    )  # Sort indices based on satellite count for plotting
    xx, yy = transformer.transform(filtered_lon[sort_ind], filtered_lat[sort_ind])
    handle = ax.scatter(
        xx - cx,
        yy - cy,
        alpha=filtered_sat[sort_ind] / filtered_sat[sort_ind].max(),
        marker=MarkerStyle("o"),
        s=10,
        c=filtered_sat[sort_ind],
        edgecolors="none",
        cmap="spring",
        label="Location",
    )
    fig.colorbar(handle, label="Satellites", shrink=0.5)

    px, py = transformer.transform(*planned_gps)

    if cable:
        planned_xy = predicted_watch_circle(
            (px - cx, py - cy), name, "grey", label="Planned"
        )
        corrected_xy = predicted_watch_circle(
            (0.0, 0.0), name, "black", label="Deployed"
        )
        for patch in planned_xy + corrected_xy:
            ax.add_patch(patch)

    ax.set_ylabel("UTM Northing Δ (m)")
    ax.set_xlabel("UTM Easting Δ (m)")
    ax.set_aspect(1.0)

    filename = FIGURES_DIR / "locations" / name.value / "watch-circle.png"
    Path(filename).parent.mkdir(parents=True, exist_ok=True)

    ax.ticklabel_format(axis="both", style="plain")
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(filename, dpi=300, bbox_inches="tight")


@plot.command(name=ClickOptions.DATASTREAM.value)
@source_options
@click.option(
    "--aggregate",
    default=Frequency.DAILY,
    type=click.Choice(Frequency, case_sensitive=False),
    required=True,
    help="Frequency for aggregation.",
)
@click.option(
    "--start",
    default=None,
    type=click.DateTime(formats=["%Y-%m-%d"]),
    help="Start date for filtering data.",
)
@click.option(
    "--end",
    default=None,
    type=click.DateTime(formats=["%Y-%m-%d"]),
    help="End date for filtering data.",
)
@click.option(
    "--size",
    nargs=2,
    default=(7.5, 4),
    type=(float, float),
    help="Figure size in inches (width, height).",
)
@plot_options
def buoys_plot_datastream(
    name: StationName,
    table: TableName,
    series: StandardNames,
    start=None,
    end=None,
    aggregate=Frequency.DAILY,
    size=(7.5, 4),
    **kwargs,
):
    """
    Plot a generic `DataStream` aggregated by either daily, weekly, or monthly. This
    will read in and concatenate all available data files for the station and table,
    then extract a deduplicated series for the data stream. The output
    is an image file formatted for a report or presentation.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    vendor_name = VendoredNames[series.name]
    local = DataFrame(df[vendor_name.value])
    units = local.columns[0][0]
    mask = ~df.index.duplicated(keep=False)
    if start is not None:
        mask &= df.index >= start
    if end is not None:
        mask &= df.index <= end
    unique = local[mask].sort_index()
    unique.index.rename("time", inplace=True)
    boxplot(
        unique,
        name.value,
        series.value,
        FIGURES_DIR / "datastream",
        units=units,
        freq=aggregate,
        figsize=size,
        **kwargs,
    )


@file_group.command(name=ClickOptions.EXPORT.value)
@station_name
@data_table
def buoys_file_export(name: StationName, table: TableName):
    """
    Export buoy data to a different format.
    """
    files = filter_buoy_flat_files(name, table)
    drop_columns = [
        "RECORD",
        "WiperPosition",
        "Sonde_External_Voltage",
        "Sonde_Battery",
        "WiperPeakCurrent",
        "TimeRecovered",
        ("Chlorophyll", "cells/mL"),
        "BGA_PE_cellsmL",
        "Pressure_Vert_Pos",
        "Depth",
    ]
    df = read_campbell_logger_files(list(files)).drop(
        columns=drop_columns, errors="ignore"
    )
    mask = ~df.index.duplicated(
        keep=False
    )  # TODO: This approach drops all duplicate index entries. Consider implementing a more nuanced duplicate handling strategy if needed.
    unique = df[mask].sort_index()
    unique.index.rename("time", inplace=True)

    def format_column(col) -> str:
        # Handle columns that are not 3-tuples gracefully
        if isinstance(col, tuple) and len(col) == 3:
            name, unit, _ = col
            return f"{name} ({unit})"
        # Fallback: just return string representation
        return str(col)

    headers = list(map(format_column, unique.columns))
    parts = list(filter(None, re.split(r"([A-Z][^A-Z]*)", table.value)))
    parts.insert(0, name.value)
    filename = "-".join(parts).lower() + ".csv"
    path = EXPORT_DIR / filename
    unique.to_csv(path, header=headers)


@file_group.command(name="gpx")
@station_name
def buoys_file_gpx(name: StationName):
    """
    Export buoy data to a different format.
    """
    table = TableName.DIAGNOSTIC
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    mask = ~df.index.duplicated(keep=False)
    unique = df[mask].sort_index()
    unique.index.rename("time", inplace=True)
    gpx = gpxpy.gpx.GPX()

    # Create first track in our GPX:
    gpx_track = gpxpy.gpx.GPXTrack()
    gpx.tracks.append(gpx_track)

    # Create first segment in our GPX track:
    gpx_segment = gpxpy.gpx.GPXTrackSegment()
    gpx_track.segments.append(gpx_segment)

    for time, row in unique.tail(24).iterrows():
        latitude = row[("Latitude", "Decimal Degrees (N=+,S=-)", "Smp")]
        longitude = row[("Longitude", "Decimal Degrees (E=+,W=-)", "Smp")]
        gpx_segment.points.append(
            gpxpy.gpx.GPXTrackPoint(latitude, longitude, elevation=0, time=time)
        )

    # You can add routes and waypoints, too...

    parts = list(filter(None, re.split(r"([A-Z][^A-Z]*)", table.value)))
    parts.insert(0, name.value)
    path = EXPORT_DIR / ("-".join(parts).lower() + ".gpx")
    with open(path, "w", encoding="utf-8") as fid:
        fid.write(gpx.to_xml())


def checksum(contents: str) -> str:
    """
    Generate a checksum for a file based on its contents.
    This can be used to create unique filenames for firmware templates.
    """
    encoded_data = contents.encode("utf-8")
    hasher = md5()
    hasher.update(encoded_data)
    return hasher.hexdigest()


@firmware.command(name=ClickOptions.TEMPLATE.value)
@station_name
@click.option("--address", required=True, help="Pakbus address")
@click.option("--client", required=True, help="Client ID")
@click.option("--file", default="buoy.dld", help="Template file")
@click.option("--latitude", required=True, help="Latitude")
@click.option("--longitude", required=True, help="Longitude")
def buoys_firmware_template(
    name: StationName,
    address: str,
    client: str,
    file: str,
    latitude: str,
    longitude: str,
):
    """
    Fill in firmware template with options passed on
    the command line.
    """
    with open(TEMPLATE_DIR / file, "r", encoding="utf-8") as fid:
        filedata = fid.read()

    for var, value in {
        "STATION_NAME": name.value,
        "PAKBUS_ADDRESS": address,
        "CLIENT_ID": client,
        "LATITUDE": latitude,
        "LONGITUDE": longitude,
    }.items():
        slug = "$" + var
        filedata = filedata.replace(slug, value)

    prefix = name.value.lower()
    filename = FIRMWARE_DIR / f"{prefix}.{checksum(filedata)}.dld"
    filename.parent.mkdir(parents=True, exist_ok=True)
    with open(filename, "w", encoding="utf-8") as fid:
        fid.write(filedata)


@firmware.command(name="lib")
@click.option("--file", default="lib.dld", help="Template file")
def buoys_firmware_library(file: str):
    """
    Fill in firmware template with options passed on
    the command line.
    """
    with open(TEMPLATE_DIR / file, "r", encoding="utf-8") as fid:
        filedata = fid.read()
    filename = FIRMWARE_DIR / f"lib.{checksum(filedata)}.dld"
    filename.parent.mkdir(parents=True, exist_ok=True)
    with open(filename, "w", encoding="utf-8") as fid:
        fid.write(filedata)


@database.command(name="upload")
@station_name
@data_table
@influx_host
@influx_api_token
def buoys_db_upload(name: StationName, table: TableName, host: str, token: str):
    """
    Upload buoy data to the database.
    """
    files = list(filter_buoy_flat_files(name, table))
    client = InfluxDBClient3(host=host, database="buoy-test-3", token=token)
    # columns = [VendoredNames.SEA_WATER_TEMPERATURE, VendoredNames.SEA_WATER_SALINITY]
    columns = [VendoredNames.SEA_WATER_TEMPERATURE]
    rename = [StandardNames[key.name].value for key in columns]
    for each in files:
        df = read_single_campbell_logger_file(each)
        subset = df[[key.value for key in columns]]
        subset.columns = rename
        subset.index.name = "time"
        with open(each, "r", encoding="utf-8") as fid:
            metadata = fid.readline().split(",")
        subset.insert(column="location", value=metadata[1].lower(), loc=0)
        subset.insert(column="thing", value=metadata[3], loc=1)
        subset.insert(column="firmware", value=metadata[5][5:-1], loc=2)
        client.write(
            subset,
            data_frame_measurement_name=table.value,
            data_frame_tag_columns=["location", "thing", "firmware"],
        )


@database.command(name="describe")
@station_name
@data_table
@influx_options
def buoys_db_describe(
    name: StationName, table: TableName, host: str, measurement: str, token: str
):
    time = "time"
    client = InfluxDBClient3(host=host, database="buoy-test", token=token)
    read_back: DataFrame = client.query(
        f"SELECT * FROM {measurement} ORDER BY {time} LIMIT 10",
        mode="pandas",
    )
    print(read_back.head())
