"""
Command line interface for working with buoy data and firmware.

Documentation is autogenerated and published to:
https://hurricane-island.github.io/pen-bay-marine-data/#penbay-buoys

Features:
- Combine column wise and row wise
- Match weather API as much as possible

"""

import re
from typing import cast, Optional
from pathlib import Path
from enum import Enum
from datetime import datetime, timedelta
from math import radians, cos, sin, sqrt, atan2
from numpy import concatenate, array, argsort
from pandas import read_csv, DataFrame, concat
from matplotlib import pyplot as plt, dates as mdates
from matplotlib.patches import Circle
from matplotlib.markers import MarkerStyle
from scipy.io import loadmat
from pyproj import Transformer
import gpxpy
import gpxpy.gpx
import click
from scipy.stats import median_abs_deviation
from lib import (
    Source,
    plot_options,
    boxplot,
    Frequency,
    ImageFormat
)
from buoys.qartod import (
    run_qartod_tests,
    TestTypes,
    get_climatology_breakpoints,
    load_and_merge_qa_configs,
    qartod_configs_option,
    qartod_test_option
)

DATA_DIR = Path(__file__).parent / "data"
FIGURES_DIR = Path(__file__).parent / "figures"
EXPORT_DIR = Path(__file__).parent / "export"
CABLE_DIR = Path(__file__).parent / "cable"
transformer = Transformer.from_crs("EPSG:4326", "EPSG:32619", always_xy=True)


class ClickOptions(Enum):
    """
    Available commands for buoy data processing.
    """

    # file and firmware commands
    LIST = "list"
    DESCRIBE = "describe"
    EXPORT = "export"
    # groups
    FILE = "file"
    BUOYS = "buoys"
    PLOT = "plot"
    # plotting commands
    TAIL = "tail"
    DATASTREAM = "datastream"


class StationName(Enum):
    """
    Supported buoy station names.
    """

    WYNKEN = "wynken"
    BLYNKEN = "blynken"


class TableName(Enum):
    """
    Supported data table names.
    """

    DIAGNOSTIC = "Ai1"
    SONDE = "SondeValues"


class VendoredNames(Enum):
    """
    Names that are used in the raw data but don't conform to CF Metadata standards.
    These are mapped to `StandardNames` for use in the CLI and plotting functions.
    """

    SEA_WATER_TEMPERATURE = "External_Temp"
    SEA_WATER_SALINITY = "Salinity"
    SEA_WATER_CHLOROPHYLL_RFU = "Chlorophyll_RFU"
    SEA_WATER_PHYCOERYTHRIN_RFU = "BGA_PE_RFU"
    BAROMETRIC_PRESSURE = "Pressure_abs"
    BATTERY_VOLTAGE = "BatteryVoltage"
    WATER_PRESSURE = "Pressure_mH2O"
    DISSOLVED_OXYGEN = "ODO"
    DISSOLVED_OXYGEN_SATURATION = "ODO_Sat"


class StandardNames(Enum):
    """
    Supported data series names.
    """

    SEA_WATER_TEMPERATURE = "sea_water_temperature"
    MASS_CONCENTRATION_OF_OXYGEN_IN_SEA_WATER = (
        "mass_concentration_of_oxygen_in_sea_water"
    )
    SEA_WATER_SALINITY = "sea_water_salinity"
    SEA_WATER_CHLOROPHYLL_RFU = "sea_water_chlorophyll_rfu"
    SEA_WATER_PHYCOERYTHRIN_RFU = "sea_water_phycoerythrin_rfu"
    BAROMETRIC_PRESSURE = "barometric_pressure"
    BATTERY_VOLTAGE = "battery_voltage"
    WATER_PRESSURE = "water_pressure"
    DISSOLVED_OXYGEN = "dissolved_oxygen"
    DISSOLVED_OXYGEN_SATURATION = "dissolved_oxygen_saturation"


# pylint: disable=too-few-public-methods
class ObservedProperty:
    """
    Abstraction for a single observed property, mapping
    multiple sources into a single Schema based on CF Metadata
    standards.
    """

    name: str
    units: str
    campbell_scientific: Source

    def __init__(self, name: str, unit: str, campbell_scientific: Source):
        self.name = name
        self.unit = unit
        self.campbell_scientific = campbell_scientific


@click.group(name=ClickOptions.BUOYS.value)
def buoys():
    """
    Command line interface for working with buoy data and firmware.
    """


@click.group(name=ClickOptions.PLOT.value)
def plot():
    """
    Commands that generate plots using buoy data.
    """


@click.group(name=ClickOptions.FILE.value)
def file_group():
    """
    Commands that interact with the buoy data file system.
    """


station_name = click.argument(
    "name", type=click.Choice(StationName, case_sensitive=False)
)
data_table = click.argument("table", type=click.Choice(TableName, case_sensitive=False))


def source_options(function):
    """
    Choose weather station and observation series. Re-usable decorator
    for commands that need to select a station and series.
    """
    function = click.argument(
        "series", type=click.Choice(StandardNames, case_sensitive=False)
    )(function)
    function = data_table(function)
    function = station_name(function)
    return function


# Subcommands assignment
buoys.add_command(plot)
buoys.add_command(file_group)


@file_group.command(name=ClickOptions.LIST.value)
def buoys_file_list():
    """
    List available stations from static data.
    """
    files = sorted(DATA_DIR.glob("*.dat"))
    seen = set()
    for f in files:
        station = f.stem.split("_")[0]
        if station not in seen:
            seen.add(station)
    for each in sorted(seen):
        print(each)


def read_single_campbell_logger_file(file: Path) -> DataFrame:
    """
    Read a single Campbell logger file and return a DataFrame.
    """
    df = read_csv(file, header=[1, 2, 3], na_values=["NAN"], parse_dates=[0])
    ts_col = df.columns[0]
    return df.set_index(ts_col)


def read_campbell_logger_files(files: list[Path]) -> DataFrame:
    """
    Read multiple Campbell logger files and return a single DataFrame.
    """
    all_data = []
    for file in sorted(files):
        df = read_single_campbell_logger_file(file)
        # Add metadata column to be able to select overlapping data later without a join
        time_recovered = file.stem.split("_")[2]
        df["TimeRecovered"] = datetime.strptime(time_recovered, "%Y-%m-%dT%H-%M")
        all_data.append(df)
    return concat(all_data).dropna(how="all", axis=1)


def filter_buoy_flat_files(name: StationName, table: TableName):
    """
    Filter buoy flat files based on command line options.
    """

    def filter_prefix(f: Path) -> bool:
        lower_name = f.stem.lower()
        station_match = name.value.lower() in lower_name
        table_match = table.value.lower() in lower_name
        return station_match and table_match

    return filter(filter_prefix, DATA_DIR.glob("*.dat"))


@file_group.command(name=ClickOptions.DESCRIBE.value)
@station_name
@data_table
def buoys_file_describe(name: StationName, table: TableName):
    """
    Summarize available data for a station.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    summary = df.describe().T.drop(columns=["25%", "75%", "std"])
    # Add Median Absolute Deviation
    mad = df.select_dtypes(include="number").apply(
         lambda x: median_abs_deviation(x, nan_policy="omit")
    )
    summary["MAD"] = mad
    print("\nSamples:\n")
    print(summary)


def load_and_subset_multifile_table(
    name: StationName,
    table: TableName,
    start: Optional[datetime],
    end: Optional[datetime],
    omit: Optional[list[str|tuple[str, str]]] = None,
) -> tuple[DataFrame, list]:
    """
    Load and subset a multi-file table for a given station and table name, returning
    a DataFrame with data between the specified start and end dates.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    if omit is not None:
        df = df.drop(columns=omit, errors="ignore")
    _end = end if end is not None else datetime.now()
    mask = (df.index <= _end)
    if start is not None:
        mask &= (df.index > start)
    df = df[mask].sort_values("TimeRecovered").drop(columns=["TimeRecovered"], errors="ignore")
    duplicates = df.index.duplicated(keep="first")
    dropped = df[duplicates].index.to_list()
    df = df[~duplicates].sort_index(kind="stable")
    resampled = df.asfreq("h")  # Resample and fill gaps with NaN to force gaps when plotting
    return resampled, dropped

def format_column_name_with_units(col: str) -> str:
    """
    Format a column name with its units if available.
    """
    if isinstance(col, tuple) and len(col) == 3:
        name, unit, _ = col
        return f"{name} ({unit})"
    return str(col)

def format_column_standard_name(col: str) -> str:
    """
    Replace with standard name if available, otherwise return the original column name.
    """
    try:
        vendor_name = VendoredNames(col[0])
        std_name = StandardNames[vendor_name.name]
        return std_name.value
    except (KeyError, ValueError):
        return col[0]

@file_group.command(name=ClickOptions.EXPORT.value)
@station_name
@data_table
def buoys_file_export(name: StationName, table: TableName):
    """
    Export buoy data to a different format.
    """
    unique, _ = load_and_subset_multifile_table(name, table, None, None, omit=[
        "RECORD",
        "WiperPosition",
        "Sonde_External_Voltage",
        "Sonde_Battery",
        "WiperPeakCurrent",
        ("Chlorophyll", "cells/mL"),
        ("Chlorophyll_ugL", "ug/L"),
        ("Pressure_abs", "psi"),
        "BGA_PE_cellsmL",
        "Pressure_Vert_Pos",
        "Depth",
        ("Conductivity_us", "us/cm"),
        ("SpConductivity_us", "us/cm"),
        ("TDS", "mg/L"),
        ("BGA_PE_ugL", "ug/L"),
        ("Conductivity_nLF", "us/cm"),
    ])
    unique.index.rename("time", inplace=True)
    headers = list(map(format_column_name_with_units, unique.columns))
    start = unique.index.min()
    end = unique.index.max()
    path = (
        EXPORT_DIR
        / name.value
        / table.name.lower()
        / (
            f"{start:%Y-%m-%d}_"
            f"{end:%Y-%m-%d}"
        )
    ).with_suffix(".csv")
    path.parent.mkdir(parents=True, exist_ok=True)
    unique.to_csv(path, header=headers)


@file_group.command(name="qartod")
@source_options
@qartod_configs_option
@qartod_test_option
def buoys_file_qartod(
    name: StationName, table: TableName, series: StandardNames, qartod: tuple[str], test: TestTypes
):
    """
    Run QARTOD tests on the buoy data and return a DataFrame with quality flags.
    """
    click.echo(f"Running QARTOD tests for {name.value} {table.value}")


@plot.command(name=ClickOptions.TAIL.value)
@source_options
@plot_options
@qartod_configs_option
@qartod_test_option
@click.option(
    "--days",
    default=30,
    type=click.IntRange(min=0),
    help="Number of days to plot backwards from the end date. Defaults to 30 days.",
)
@click.option(
    "--end",
    default=datetime.now(),
    type=click.DateTime(formats=["%Y-%m-%d"]),
    help="End date for the analysis and plotting. Defaults to the current date and time.",
)
@click.option(
    "--scale/--no-scale",
    is_flag=True,
    default=False,
    help="Scale the output plot to remaining data, otherwise use the full range. Defaults to True.",
)
def buoys_plot_tail(
    name: StationName,
    table: TableName,
    series: StandardNames,
    qartod: tuple[str],
    days: int,
    test: TestTypes,
    end: datetime,
    image_format: ImageFormat,
    scale: bool
):
    """
    Plot the most recent data from a buoy for a single data stream.
    """
    start: datetime = end - timedelta(days=days)
    df, dropped = load_and_subset_multifile_table(name, table, start, end)
    if df.empty:
        raise click.ClickException(
            f"No local data for {name.value} {table.value} between {start} and {end}."
        )
    renamed = []
    units = {}
    for col in df.columns:
        try:
            vendor_name = VendoredNames(col[0])
            std_name = StandardNames[vendor_name.name]
            renamed.append(std_name.value)
        except (KeyError, ValueError):
            renamed.append(col[0])
        units[renamed[-1]] = col[1]
    df.columns = renamed

    fig, ax = plt.subplots(figsize=(7.5, 3))

    ax.plot(
        df.index,
        df[series.value],
        color="grey",
        linestyle="dashed",
        linewidth=1,
        zorder=2,
        label="raw",
    )
    ylim = (None, None)
    suffix = "no-qa"
    if len(qartod) > 0:
        config_key_value = load_and_merge_qa_configs(qartod)
        breaks = get_climatology_breakpoints(config_key_value, series.value)
        suffix = "-".join(Path(each).stem for each in qartod) + "-" + test.value
        gps, _ = load_and_subset_multifile_table(name, TableName.DIAGNOSTIC, start, end)
        df["Latitude"] = gps["Latitude"].to_numpy().flatten()
        df["Longitude"] = gps["Longitude"].to_numpy().flatten()
        qa = run_qartod_tests(df, config_key_value).get_group(series.value)
        gaps = cast(DataFrame, df.loc[qa["gap"] == 3, series.value])
        qa = qa[test.value]
        suspect = cast(DataFrame, df.loc[qa == 3, series.value])
        failed = cast(DataFrame, df.loc[qa == 4, series.value])
        remaining = df.loc[((qa < 3) | (qa == 9)), series.value].asfreq("h")

        ax.vlines(
            gaps.index,
            ymin=0,
            ymax=1,
            color="pink",
            linewidth=1,
            label="gap",
            transform=ax.get_xaxis_transform(),
            zorder=0
        )
        ax.vlines(
            breaks,
            ymin=0,
            ymax=1,
            color="black",
            linewidth=1,
            linestyle="dotted",
            label="climatology change",
            transform=ax.get_xaxis_transform(),
            zorder=0
        )
        ax.scatter(
            suspect.index,
            suspect,
            label="suspect",
            color="orange",
            marker="x",
            zorder=1,
        )
        ax.scatter(
            failed.index, failed, label="failed", color="red", marker="x", zorder=1
        )
        ax.plot(
            remaining.index,
            remaining,
            color="black",
            linestyle="solid",
            linewidth=1,
            zorder=2,
            label="filtered",
        )
        if scale:
            ylim = (remaining.min(), remaining.max())

    ax.vlines(
        dropped,
        ymin=0,
        ymax=1,
        color="cyan",
        linewidth=1,
        label="duplicate",
        transform=ax.get_xaxis_transform(),
        zorder=0
    )
    start = df.index.min()
    end = df.index.max()
    _days = (end - start).days
    display_name = series.value.replace("_", " ").title()
    if start.year == end.year:
        year_range = f"{start.year}"
    else:
        year_range = f"{start.year}-{end.year}"
    ax.set_title(f"{name.value} {display_name} {year_range} ({test.value.replace('_', ' ')})".title())
    ax.set_xlabel("Date")
    ax.xaxis.set_tick_params(rotation=45)
    ax.set_xlim(start, end)
    ax.set_ylim(*ylim)
    ax.xaxis.set_major_locator(mdates.DayLocator(interval=(_days // 8) + 2))
    ax.xaxis.set_minor_locator(mdates.DayLocator(interval=1))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))  # Customize format
    if units is not None:
        ax.set_ylabel(f"{units[series.value]}")
    ax.legend(bbox_to_anchor=(1, 1), loc='upper left')
    fig.tight_layout()
    filepath = (
        FIGURES_DIR
        / ClickOptions.TAIL.value
        / name.value
        / table.value
        / series.value
        / (
            f"{start:%Y-%m-%d}_"
            f"{end:%Y-%m-%d}_"
            f"{suffix}."
            f"{image_format.value}"
        )
    )
    filepath.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(filepath, dpi=300, bbox_inches="tight")
    click.echo(f"Saved plot to {filepath}")
    plt.close(fig)  # clean up when testing to avoid memory issues with pytest and matplotlib


@plot.command(name="cable")
@station_name
def buoys_plot_cable(name: StationName):
    """
    Plot the mooring tension diagram from the WHOI cable simulation.
    """
    low = CABLE_DIR / f"{name.value}-low.mat"
    high = CABLE_DIR / f"{name.value}-high.mat"
    if not low.exists() or not high.exists():
        raise click.ClickException(
            f"Missing cable simulation .mat files for station '{name.value}' (expected {low.name} and {high.name} under {CABLE_DIR})"
        )
    low_data = loadmat(low)
    high_data = loadmat(high)
    fig, ax = plt.subplots(figsize=(4, 3))
    x = concatenate([low_data["x"], high_data["x"]])
    y = concatenate([low_data["z"], high_data["z"]])
    z = concatenate([low_data["T"], high_data["T"]])
    handle = ax.scatter(x, y, c=z, s=2, cmap="spring", label="Mooring")
    ax.vlines(
        low_data["x"].max(),
        ymin=0.0,
        ymax=low_data["z"].max(),
        colors="black",
        linestyles="solid",
        label="Low Tide",
    )
    ax.vlines(
        high_data["x"].max(),
        ymin=0.0,
        ymax=high_data["z"].max(),
        colors="black",
        linestyles="dashed",
        label="High Tide",
    )
    ax.hlines(
        high_data["depth"],
        xmin=0.0,
        xmax=high_data["x"].max(),
        colors="black",
        linestyles="dashed",
    )
    ax.hlines(
        low_data["depth"],
        xmin=0.0,
        xmax=low_data["x"].max(),
        colors="black",
        linestyles="solid",
    )
    ax.set_aspect(1.0)
    fig.colorbar(handle, label="Tension (N)", shrink=0.5)
    ax.set_ylim(y.min(), None)
    ax.set_xlim(x.min(), None)
    ax.set_xlabel("Displacement (m)")
    ax.set_ylabel("Water Level (m)")
    ax.legend(loc="best")
    filename = FIGURES_DIR / "cable" / name.value / "mooring-tension.png"
    Path(filename).parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(filename, bbox_inches="tight", dpi=300)


def predicted_watch_circle(
    center_xy: tuple[float, float],
    station: StationName,
    color: str,
    scale: float = 1.0,
    label: str | None = None,
) -> list[Circle]:
    """
    Generate a predicted watch circle based on the planned deployment location.
    """
    predicted: list[Circle] = []
    for each, circle_label, ls in [("low", label, "solid"), ("high", None, "dashed")]:
        mat_path = CABLE_DIR / f"{station.value}-{each}.mat"
        if not mat_path.exists():
            raise click.ClickException(f"Missing cable simulation file: {mat_path}")
        data = loadmat(mat_path)
        radius = float(data["x"].max()) * scale
        predicted.append(
            Circle(
                center_xy,
                radius=radius,
                color=color,
                fill=False,
                linestyle=ls,
                label=circle_label,
            )
        )
    return predicted


def haversine(lon1, lat1, lon2, lat2):
    R = 6371000.0  # Earth radius in meters

    phi1, phi2 = radians(lat1), radians(lat2)
    delta_phi = radians(lat2 - lat1)
    delta_lambda = radians(lon2 - lon1)
    a = sin(delta_phi / 2) ** 2 + cos(phi1) * cos(phi2) * sin(delta_lambda / 2) ** 2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c  # Distance in meters


@plot.command(name="locations")
@station_name
@click.option("--latitude", required=True, type=float)
@click.option("--longitude", required=True, type=float)
@click.option(
    "--distance",
    required=True,
    type=float,
    help="filter GPS points by distance from planned deployment location (meters)",
)
@click.option(
    "--satellites", required=True, type=int, help="minimum number of satellites"
)
@click.option(
    "--start",
    default=None,
    type=click.DateTime(formats=["%Y-%m-%d"]),
    help="Start date for filtering GPS points.",
)
@click.option(
    "--end",
    default=None,
    type=click.DateTime(formats=["%Y-%m-%d"]),
    help="End date for filtering GPS points.",
)
@click.option(
    "--cable",
    is_flag=True,
    help="include predicted watch circle from WHOI cable simulation",
)
def buoys_plot_locations(
    name, latitude, longitude, distance=100.0, satellites=4, start=None, end=None, cable=False,
):
    """
    Plot the lat and long of the buoy hourly over the course of the deployment period.
    This only uses historical data contained in local raw files. Compare it to the
    deployment location of the anchor and the watch circle predicted by WHOI Cable
    simulations.
    """
    table = TableName.DIAGNOSTIC
    lat_name = "Latitude"
    lon_name = "Longitude"
    sat_name = "GPSSatellitesInView"
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    lat = df[lat_name].to_numpy().flatten()
    lon = df[lon_name].to_numpy().flatten()
    satellite_count = df[sat_name].to_numpy().flatten()
    planned_gps = (longitude, latitude)  # original

    def compute_distance(gps):
        return haversine(*planned_gps, *gps)

    mask = (
        (array(list(map(compute_distance, zip(lon, lat)))) < distance)
        & (satellite_count >= satellites)
    )
    if start is not None:
        mask &= df.index >= start
    if end is not None:
        mask &= df.index <= end
    filtered_lon = lon[mask]
    filtered_lat = lat[mask]
    if filtered_lon.size == 0:
        raise click.ClickException(
            "No GPS points remain after filtering; try increasing --distance, lowering --satellites, or adjusting the date filter."
        )
    cx, cy = transformer.transform(filtered_lon.mean(), filtered_lat.mean())
    filtered_sat = satellite_count[mask]

    fig, ax = plt.subplots(figsize=(3, 4))

    sort_ind = argsort(
        filtered_sat
    )  # Sort indices based on satellite count for plotting
    xx, yy = transformer.transform(filtered_lon[sort_ind], filtered_lat[sort_ind])
    handle = ax.scatter(
        xx - cx,
        yy - cy,
        alpha=filtered_sat[sort_ind] / filtered_sat[sort_ind].max(),
        marker=MarkerStyle("o"),
        s=10,
        c=filtered_sat[sort_ind],
        edgecolors="none",
        cmap="spring",
        label="Location",
    )
    fig.colorbar(handle, label="Satellites", shrink=0.5)

    px, py = transformer.transform(*planned_gps)

    if cable:
        planned_xy = predicted_watch_circle(
            (px - cx, py - cy), name, "grey", label="Planned"
        )
        corrected_xy = predicted_watch_circle(
            (0.0, 0.0), name, "black", label="Deployed"
        )
        for patch in planned_xy + corrected_xy:
            ax.add_patch(patch)

    ax.set_ylabel("UTM Northing Δ (m)")
    ax.set_xlabel("UTM Easting Δ (m)")
    ax.set_aspect(1.0)

    filename = FIGURES_DIR / "locations" / name.value / "watch-circle.png"
    Path(filename).parent.mkdir(parents=True, exist_ok=True)

    ax.ticklabel_format(axis="both", style="plain")
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(filename, dpi=300, bbox_inches="tight")


@plot.command(name=ClickOptions.DATASTREAM.value)
@source_options
@click.option(
    "--aggregate",
    default=Frequency.DAILY,
    type=click.Choice(Frequency, case_sensitive=False),
    required=True,
    help="Frequency for aggregation.",
)
@click.option(
    "--start",
    default=None,
    type=click.DateTime(formats=["%Y-%m-%d"]),
    help="Start date for filtering data.",
)
@click.option(
    "--end",
    default=None,
    type=click.DateTime(formats=["%Y-%m-%d"]),
    help="End date for filtering data.",
)
@click.option(
    "--size",
    nargs=2,
    default=(7.5, 4),
    type=(float, float),
    help="Figure size in inches (width, height).",
)
@plot_options
def buoys_plot_datastream(
    name: StationName,
    table: TableName,
    series: StandardNames,
    start=None,
    end=None,
    aggregate=Frequency.DAILY,
    size=(7.5, 4),
    **kwargs,
):
    """
    Plot a generic `DataStream` aggregated by either daily, weekly, or monthly. This
    will read in and concatenate all available data files for the station and table,
    then extract a deduplicated series for the data stream. The output
    is an image file formatted for a report or presentation.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    vendor_name = VendoredNames[series.name]
    local = DataFrame(df[vendor_name.value])
    units = local.columns[0][0]
    mask = ~df.index.duplicated(keep=False)
    if start is not None:
        mask &= df.index >= start
    if end is not None:
        mask &= df.index <= end
    unique = local[mask].sort_index()
    unique.index.rename("time", inplace=True)
    boxplot(
        unique,
        name.value,
        series.value,
        FIGURES_DIR / "datastream",
        units=units,
        freq=aggregate,
        figsize=size,
        **kwargs,
    )


@file_group.command(name="gpx")
@station_name
def buoys_file_gpx(name: StationName):
    """
    Export buoy data to a different format.
    """
    table = TableName.DIAGNOSTIC
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    mask = ~df.index.duplicated(keep=False)
    unique = df[mask].sort_index()
    unique.index.rename("time", inplace=True)
    gpx = gpxpy.gpx.GPX()

    # Create first track in our GPX:
    gpx_track = gpxpy.gpx.GPXTrack()
    gpx.tracks.append(gpx_track)

    # Create first segment in our GPX track:
    gpx_segment = gpxpy.gpx.GPXTrackSegment()
    gpx_track.segments.append(gpx_segment)

    for time, row in unique.tail(24).iterrows():
        latitude = row[("Latitude", "Decimal Degrees (N=+,S=-)", "Smp")]
        longitude = row[("Longitude", "Decimal Degrees (E=+,W=-)", "Smp")]
        gpx_segment.points.append(
            gpxpy.gpx.GPXTrackPoint(latitude, longitude, elevation=0, time=time)
        )

    # You can add routes and waypoints, too...

    parts = list(filter(None, re.split(r"([A-Z][^A-Z]*)", table.value)))
    parts.insert(0, name.value)
    path = EXPORT_DIR / ("-".join(parts).lower() + ".gpx")
    with open(path, "w", encoding="utf-8") as fid:
        fid.write(gpx.to_xml())


@file_group.command(name="derivatives")
@station_name
@data_table
@click.argument(
    "series",
    type=click.Choice(StandardNames, case_sensitive=False),
)
@click.option(
    "--percentile",
    "-p",
    default=(0.90, 0.95, 0.99),
    multiple=True,
    type=float,
    help="Percentiles to calculate for the summary statistics. Accepts multiple values, e.g., -p 0.90 -p 0.95 -p 0.99",
)
def buoys_file_first_and_second_derivative(
    name: StationName,
    table: TableName,
    series: StandardNames,
    percentile: tuple[float, float, float]
):
    """
    Calculate the first and second derivative of a time series to identify
    rapid changes and spikes in the series. Performs hourly resampling to
    fill gaps, so that time differences are consistent. The output values
    are in units per second and per hour, respectively, to use as inputs 
    for a QARTOD configuration file.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    vendor_name = VendoredNames[series.name]
    ds = df[vendor_name.value]
    ds = ds.sort_index()
    ds = ds[~ds.index.duplicated(keep="first")].asfreq("h")  # resample filling gaps with NaN
    slope = ds.diff()
    summary = DataFrame(
        data={
            "|dy/dt| (/s)": (slope.abs() / 3600.0).squeeze(),
            "|d²y/dt²| (/hr)": slope.diff().abs().squeeze()
        },
        index=ds.index
    ).describe(percentiles=sorted(percentile)).map('{:.8f}'.format)
    click.echo(summary)
