# pylint: disable=too-many-locals
"""
Command line interface for working with buoy data and firmware.

Documentation is autogenerated and published to:
https://hurricane-island.github.io/pen-bay-marine-data/#penbay-buoys

Features:
- Combine column wise and row wise
- Match weather API as much as possible

"""

import re
from pathlib import Path
from enum import Enum
from datetime import datetime
from hashlib import md5
from pandas import read_csv, DataFrame, concat
import gpxpy
import gpxpy.gpx
import click
from lib import Source, plot_tail, plot_options, boxplot

DATA_DIR = Path(__file__).parent / "data"
FIGURES_DIR = Path(__file__).parent / "figures"
EXPORT_DIR = Path(__file__).parent / "export"
FIRMWARE_DIR = Path(__file__).parent / "firmware"
TEMPLATE_DIR = Path(__file__).parent / "templates"

class ClickOptions(Enum):
    """
    Available commands for buoy data processing.
    """

    # file and firmware commands
    LIST = "list"
    DESCRIBE = "describe"
    TEMPLATE = "template"
    EXPORT = "export"
    # groups
    FILE = "file"
    BUOYS = "buoys"
    PLOT = "plot"
    FIRMWARE = "firmware"
    # plotting commands
    TAIL = "tail"
    DAILY = "daily"


class StationName(Enum):
    """
    Supported buoy station names.
    """

    WYNKEN = "wynken"
    BLYNKEN = "blynken"


class TableName(Enum):
    """
    Supported data table names.
    """

    DIAGNOSTIC = "Ai1"
    SONDE = "SondeValues"

class VendoredNames(Enum):
    """
    Names that are used in the raw data but don't conform to CF Metadata standards.
    These are mapped to `StandardNames` for use in the CLI and plotting functions.
    """

    SEA_WATER_TEMPERATURE = "External_Temp"
    SEA_WATER_SALINITY = "Salinity"

class StandardNames(Enum):
    """
    Supported data series names.
    """

    SEA_WATER_TEMPERATURE = "sea_water_temperature"
    MASS_CONCENTRATION_OF_OXYGEN_IN_SEA_WATER = (
        "mass_concentration_of_oxygen_in_sea_water"
    )
    SEA_WATER_SALINITY = "sea_water_salinity"


# pylint: disable=too-few-public-methods
class ObservedProperty:
    """
    Abstraction for a single observed property, mapping
    multiple sources into a single Schema based on CF Metadata
    standards.
    """

    name: str
    units: str
    campbell_scientific: Source

    def __init__(self, name: str, unit: str, campbell_scientific: Source):
        self.name = name
        self.unit = unit
        self.campbell_scientific = campbell_scientific


@click.group(name=ClickOptions.BUOYS.value)
def buoys():
    """
    Command line interface for working with buoy data and firmware.
    """

@click.group(name=ClickOptions.FIRMWARE.value)
def firmware():
    """
    Command line interface for working with buoy data and firmware.
    """


@click.group(name=ClickOptions.PLOT.value)
def plot():
    """
    Commands that generate plots using buoy data.
    """


@click.group(name=ClickOptions.FILE.value)
def file_group():
    """
    Commands that interact with the buoy data file system.
    """

station_name = click.argument("name", type=click.Choice(StationName, case_sensitive=False))
data_table = click.argument("table", type=click.Choice(TableName, case_sensitive=False))

def source_options(function):
    """
    Choose weather station and observation series. Re-usable decorator
    for commands that need to select a station and series.
    """
    function = click.argument(
        "series", type=click.Choice(StandardNames, case_sensitive=False)
    )(function)
    function = data_table(function)
    function = station_name(function)
    return function


# Subcommands assignment
buoys.add_command(plot)
buoys.add_command(firmware)
buoys.add_command(file_group)


@file_group.command(name=ClickOptions.LIST.value)
def buoy_file_list():
    """
    List available stations from static data.
    """
    files = sorted(DATA_DIR.glob("*.dat"))
    seen = set()
    for f in files:
        station = f.stem.split("_")[0]
        if station not in seen:
            seen.add(station)
    for each in sorted(seen):
        print(each)


def read_single_campbell_logger_file(file: Path) -> DataFrame:
    """
    Read a single Campbell logger file and return a DataFrame.
    """
    df = read_csv(file, header=[1, 2, 3], na_values=["NAN"], parse_dates=[0])
    ts_col = df.columns[0]
    return df.set_index(ts_col)


def read_campbell_logger_files(files: list[Path]) -> DataFrame:
    """
    Read multiple Campbell logger files and return a single DataFrame.
    """
    all_data = []
    for file in sorted(files):
        df = read_single_campbell_logger_file(file)
        # Add metadata column to be able to select overlapping data later without a join
        time_recovered = file.stem.split("_")[2]
        df["TimeRecovered"] = datetime.strptime(time_recovered, "%Y-%m-%dT%H-%M")
        all_data.append(df)
    return concat(all_data).dropna(how="all", axis=1)


def filter_buoy_flat_files(name: StationName, table: TableName):
    """
    Filter buoy flat files based on command line options.
    """
    def filter_prefix(f: Path) -> bool:
        lower_name = f.stem.lower()
        station_match = name.value.lower() in lower_name
        table_match = table.value.lower() in lower_name
        return station_match and table_match

    return filter(filter_prefix, DATA_DIR.glob("*.dat"))


@file_group.command(name=ClickOptions.DESCRIBE.value)
@station_name
@data_table
def buoy_file_describe(name: StationName, table: TableName):
    """
    Summarize available data for a station.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    summary = df.describe().T.drop(columns=["25%", "50%", "75%", "std", "mean"])
    print("\nSamples:\n")
    print(summary)


@plot.command(name=ClickOptions.TAIL.value)
@source_options
@plot_options
def buoy_plot_tail(
    name: StationName, table: TableName, series: StandardNames, **kwargs
):
    """
    Plot the most recent data from a buoy for a single data stream.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    vendor_name = VendoredNames[series.name]
    local = DataFrame(df[vendor_name.value])
    units = local.columns[0][0]
    as_series = local.squeeze()
    as_series.name = "local"
    plot_tail(
        as_series,
        None,
        name.value,
        series.value,
        prefix=f"buoys/figures/{ClickOptions.TAIL.value}",
        units=units,
        **kwargs,
    )


@plot.command(name=ClickOptions.DAILY.value)
@source_options
@plot_options
def buoy_plot_daily(name: StationName, table: TableName, series: StandardNames, **kwargs):
    """
    Plot a single `DataStream` aggregated by day.
    """
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    vendor_name = VendoredNames[series.name]
    local = DataFrame(df[vendor_name.value])
    units = local.columns[0][0]
    mask = ~df.index.duplicated(keep=False)
    unique = local[mask].sort_index()
    unique.index.rename("time", inplace=True)
    prefix = FIGURES_DIR / ClickOptions.DAILY.value
    boxplot(unique, name.value, series.value, str(prefix), units=units, **kwargs)


@file_group.command(name=ClickOptions.EXPORT.value)
@station_name
@data_table
def buoy_file_export(name: StationName, table: TableName):
    """
    Export buoy data to a different format.
    """
    files = filter_buoy_flat_files(name, table)
    drop_columns = [
        "RECORD", 
        "WiperPosition",
        "Sonde_External_Voltage",
        "Sonde_Battery",
        "WiperPeakCurrent",
        "TimeRecovered",
        ("Chlorophyll", "cells/mL"),
        "BGA_PE_cellsmL",
        "Pressure_Vert_Pos",
        "Depth"
    ]
    df = read_campbell_logger_files(list(files)).drop(columns=drop_columns, errors='ignore')
    mask = ~df.index.duplicated(keep=False)  # TODO: This approach drops all duplicate index entries. Consider implementing a more nuanced duplicate handling strategy if needed.
    unique = df[mask].sort_index()
    unique.index.rename("time", inplace=True)
    def format_column(col) -> str:
        # Handle columns that are not 3-tuples gracefully
        if isinstance(col, tuple) and len(col) == 3:
            name, unit, _ = col
            return f"{name} ({unit})"
        # Fallback: just return string representation
        return str(col)
    headers = list(map(format_column, unique.columns))
    parts = list(filter(None, re.split(r'([A-Z][^A-Z]*)', table.value)))
    parts.insert(0, name.value)
    filename = "-".join(parts).lower() + ".csv"
    path = EXPORT_DIR / filename
    unique.to_csv(path, header=headers)

@file_group.command(name='gpx')
@station_name
def buoy_file_gpx(name: StationName):
    """
    Export buoy data to a different format.
    """
    table = TableName.DIAGNOSTIC
    files = filter_buoy_flat_files(name, table)
    df = read_campbell_logger_files(list(files))
    mask = ~df.index.duplicated(keep=False)
    unique = df[mask].sort_index()
    unique.index.rename("time", inplace=True)
    gpx = gpxpy.gpx.GPX()

    # Create first track in our GPX:
    gpx_track = gpxpy.gpx.GPXTrack()
    gpx.tracks.append(gpx_track)

    # Create first segment in our GPX track:
    gpx_segment = gpxpy.gpx.GPXTrackSegment()
    gpx_track.segments.append(gpx_segment)

    for time, row in unique.tail(24).iterrows():
        latitude = row[('Latitude', 'Decimal Degrees (N=+,S=-)', "Smp")]
        longitude = row[('Longitude', 'Decimal Degrees (E=+,W=-)', "Smp")]
        gpx_segment.points.append(gpxpy.gpx.GPXTrackPoint(latitude, longitude, elevation=0, time=time))

    # You can add routes and waypoints, too...

    parts = list(filter(None, re.split(r'([A-Z][^A-Z]*)', table.value)))
    parts.insert(0, name.value)
    path = EXPORT_DIR / ("-".join(parts).lower() + ".gpx")
    with open(path, "w", encoding="utf-8") as fid:
        fid.write(gpx.to_xml())

def checksum(contents: str) -> str:
    """
    Generate a checksum for a file based on its contents.
    This can be used to create unique filenames for firmware templates.
    """
    encoded_data = contents.encode("utf-8")
    hasher = md5()
    hasher.update(encoded_data)
    return hasher.hexdigest()

@firmware.command(name=ClickOptions.TEMPLATE.value)
@station_name
@click.option("--address", required=True, help="Pakbus address")
@click.option("--client", required=True, help="Client ID")
@click.option("--file", default="buoy.dld", help="Template file")
def buoys_firmware_template(name: StationName, address: str, client: str, file: str):
    """
    Fill in firmware template with options passed on
    the command line.
    """
    with open(TEMPLATE_DIR / file, "r", encoding="utf-8") as fid:
        filedata = fid.read()

    for var, value in {
        "STATION_NAME": name.value,
        "PAKBUS_ADDRESS": address,
        "CLIENT_ID": client,
    }.items():
        slug = "$" + var
        filedata = filedata.replace(slug, value)

    prefix = name.value.lower()
    filename = FIRMWARE_DIR / f"{prefix}.{checksum(filedata)}.dld"
    filename.parent.mkdir(parents=True, exist_ok=True)
    with open(filename, "w", encoding="utf-8") as fid:
        fid.write(filedata)


@firmware.command(name="lib")
@click.option("--file", default="lib.dld", help="Template file")
def buoys_firmware_library(file: str):
    """
    Fill in firmware template with options passed on
    the command line.
    """
    with open(TEMPLATE_DIR / file, "r", encoding="utf-8") as fid:
        filedata = fid.read()
    filename = FIRMWARE_DIR / f"lib.{checksum(filedata)}.dld"
    filename.parent.mkdir(parents=True, exist_ok=True)
    with open(filename, "w", encoding="utf-8") as fid:
        fid.write(filedata)
