{
 "title": "Weather",
 "description": "Real-time meteorological data for Penobscot Bay, Maine. Part of the Pen Bay Marine Data Project at Hurricane Island Center for Science and Leadership.",
 "tags": [
  "Weather",
  "Climate",
  "Sensors"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Pen Bay Marine Data Project",
   "type": "text",
   "description": "Information about the project and data sources.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# About\n\nThese data are produced by Hurricane Island Center for Science and Leadership through our Pen Bay Marine Data project.\n\nWe manage a network of moored ocean observing buoys, weather stations, and radio network gateways near Hurricane Island, Rockland, and Islesboro, and will continue to expand in years to come.\n\nOur ocean observing systems are funded through the Maine Coastal and Marine Climate Fund, and would not be possible without the generous support of many partner organizations and individuals.\n\n## Contact\n\nFor more information please contact Nicholas Keeney (nkeeney@hurricaneisland.net)."
   }
  },
  { "title": "Rockland, Maine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature & Humidity",
   "type": "timeseries",
   "description": "Weather station at The Apprenticeshop in Rockland Maine. Davis Vantage 2 Pro model.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"outTemp\", \"outHumidity\" FROM \"observations\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"binding\" = 'archive' "
    }
   ]
  },
  {
   "title": "Air Pressure",
   "type": "timeseries",
   "description": "Weather station at The Apprenticeshop in Rockland Maine. Davis Vantage 2 Pro model.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"barometer\" FROM \"observations\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"binding\" = 'archive' "
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"barometer\" FROM \"observations\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Daylight",
   "type": "timeseries",
   "description": "Weather station at The Apprenticeshop in Rockland Maine. Davis Vantage 2 Pro model.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"UV\", \"radiation\" FROM \"observations\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"binding\" = 'archive' "
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "description": "Weather station at The Apprenticeshop in Rockland Maine. Davis Vantage 2 Pro model.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"windSpeed\", \"windGust\" FROM \"observations\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"binding\" = 'archive' "
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "operato-windrose-panel",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  (\"windDir\" + 180) % 360 AS \"wind_direction\", \n  \"windSpeed\" AS \"wind_speed\" \nFROM \"observations\"\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  }
 ]
}