name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.3 # Pin to a specific version
        with:
          run-install: true # Install dependencies
      - name: Sphinx build
        run: |
          pixi run sphinx-build -b html docs www
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: www/
          force_orphan: true